package poly.core.persistence.entity;
// Generated Oct 10, 2018 8:57:07 PM by Hibernate Tools 4.3.1

/**
 * CartDetail generated by hbm2java
 */
public class CartDetail implements java.io.Serializable {

    private int id;
    private Cart cart;
    private int productQuantity;
    private Product product;

    public CartDetail() {
    }

    public CartDetail(Cart cart, Product product, int productQuantity) {
       this.cart = cart;
       this.product = product;
       this.productQuantity = productQuantity;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Cart getCart() {
        return this.cart;
    }

    public void setCart(Cart cart) {
        this.cart = cart;
    }

    public int getProductQuantity() {
        return this.productQuantity;
    }

    public void setProductQuantity(int productQuantity) {
        this.productQuantity = productQuantity;
    }

    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

}
