package poly.core.persistence.entity;
// Generated Oct 10, 2018 8:57:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private int id;
     private User user;
     private Date createdDate;
     private int status;
     private Set<CartDetail> cartDetails = new HashSet<CartDetail>(0);
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public Cart() {
    }

    public Cart(User user, Date createdDate) {
        this.user = user;
        this.createdDate = createdDate;
        this.status = 0;
    }
	
    public Cart(int id, User user, Date createdDate) {
        this.id = id;
        this.user = user;
        this.createdDate = createdDate;
    }
    public Cart(int id, User user, Date createdDate, int status, Set<CartDetail> cartDetails, Set<Invoice> invoices) {
       this.id = id;
       this.user = user;
       this.createdDate = createdDate;
       this.status = status;
       this.cartDetails = cartDetails;
       this.invoices = invoices;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set<CartDetail> getCartDetails() {
        return this.cartDetails;
    }
    
    public void setCartDetails(Set<CartDetail> cartDetails) {
        this.cartDetails = cartDetails;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


