package poly.core.persistence.entity;
// Generated Oct 10, 2018 8:57:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private int id;
     private Cart cart;
     private User user;
     private Date createdDate;
     private int status;

    public Invoice() {
    }

    public Invoice(Cart cart, User user) {
        this.cart = cart;
        this.user = user;
        this.createdDate = new Date();
        this.status = 0;
    }
	
    public Invoice(int id, Cart cart, Date createdDate) {
        this.id = id;
        this.cart = cart;
        this.createdDate = createdDate;
    }
    public Invoice(int id, Cart cart, Date createdDate, int status) {
       this.id = id;
       this.cart = cart;
       this.createdDate = createdDate;
       this.status = status;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cart getCart() {
        return this.cart;
    }
    
    public void setCart(Cart cart) {
        this.cart = cart;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    
    
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


