package poly.core.persistence.entity;
// Generated Oct 10, 2018 8:57:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private Role role;
     private String username;
     private String password;
     private String fullname;
     private String email;
     private String phone;
     private String address;
     private Set<Cart> carts = new HashSet<Cart>(0);
     private Set<Cart> invoices = new HashSet<Cart>(0);

    public User() {
    }

	
    public User(int id, Role role, String username, String password, String fullname, String email, String phone, String address) {
        this.id = id;
        this.role = role;
        this.username = username;
        this.password = password;
        this.fullname = fullname;
        this.email = email;
        this.phone = phone;
        this.address = address;
    }
    public User(int id, Role role, String username, String password, String fullname, String email, String phone, String address, Set<Cart> carts, Set<Cart> invoices) {
       this.id = id;
       this.role = role;
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.email = email;
       this.phone = phone;
       this.address = address;
       this.carts = carts;
       this.invoices = invoices;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set<Cart> getCarts() {
        return this.carts;
    }
    
    public void setCarts(Set<Cart> carts) {
        this.carts = carts;
    }

    public Set<Cart> getInvoices() {
        return invoices;
    }

    public void setInvoices(Set<Cart> invoices) {
        this.invoices = invoices;
    }




}


